server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CelesteGc/CTD-ParcialEspecializacionBackend/tree/main/configs
